hisat2_align:
    nodes: 1 
    threads: 12
    mem_mb: 36000
    time: 2160

samsort:
    nodes: 1
    threads: 12
    mem_mb: 24000
    time: 360  

stringtie:
    nodes: 1 
    threads: 16
    mem_mb: 32000
    time: 720

stringtie_merge:
    nodes: 1
    threads: 1
    mem_mb: 20000 
    time: 360

transdecoder_longorfs:
   nodes: 1
   threads: 1
   mem_mb: 50000
   time: 1380  

"""
star_1stpass:
    nodes: 1 
    threads: 8
    mem_mb: 64000
    time: 1920

star_2ndpass:
    nodes: 1
    threads: 8
    mem_mb: 64000
    time: 1920

scallop:
    nodes: 1
    threads: 1
    mem_mb: 32000
    time: 420

taco:
    nodes: 1
    threads: 16 
    mem_mb: 32000
    time: 180
"""
